### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by protezio** [svenove/ESPHome-ESP32-2424S012-LVGL#1]
I noticed that after about 4-5 hours the device restarts... it seems to be due to the memory no longer being available....
do you agree?

**Comment by svenove** [comment]
Mine is currently not being used. I haven’t noticed any reboots, but a reboot would just take a few seconds any way, so how do you notice it rebooting?

**Comment by protezio** [comment]
I added

```
logger:
  level: debug
debug:
  update_interval: 30s

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
```

for now I noticed a restart every 3 hours so as a workaround I put an automatic restart ... because it often didn't restart on its own

**Comment by svenove** [comment]
Is this still an issue you’re having?
I haven’t had time to test it myself yet.

**Comment by protezio** [comment]
> Is this still an issue you’re having? I haven’t had time to test it myself yet.

with the latest updates it seems no problem so far
