### ISSUE TITLE
Does not fit in my display

### ISSUE THREAD

**Issue by ps1x** [svenove/ESPHome-ESP32-2424S012-LVGL#2]
Hello and thank you for sharing, unfortunately your code somehow does not fit my display with following message:
`Error: The program size (1999120 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
RAM:   [==        ]  17.8% (used 58228 bytes from 327680 bytes)
Flash: [==========]  108.9% (used 1999120 bytes from 1835008 bytes)`

What can i do here?

**Comment by svenove** [comment]
Are you sure it’s the “ESP32-2424S012” you have? It’s listed as having 4MB RAM, but yours seem to perhaps only have 2 MB?

You could try to remove page 2 and 3 and see if it will fit then.
