### ISSUE TITLE
Not able to compile source with ESPHome 2024.11.1

### ISSUE THREAD

**Issue by ToViNi** [svenove/ESPHome-ESP32-2424S012-LVGL#3]
If I include the custom component I get this error:

src/esphome/components/lvgl/lvgl_esphome.h:231:27: error: 'image_type_to_width_stride' is not a member of 'esphome::image'

If I don't, and use the LVGL in Esphome 2024.11 I get this:

Error on - lvgl.indicator.line.update: (Line 224)  and all the other updates.

Can you update your code to support the native LVGL component in ESPHome 2024.11?   

Thanks!  

Regards from Fredrikstad :)

**Comment by svenove** [comment]
I just discovered the same problem yesterday!
Think I’ve been able to fix it. Will upload the updated code later today or tomorrow. :)
